CREATE TABLE MEDIA 
(	
    MEDIA_CD VARCHAR2(2 BYTE), 
    MEDIA_NM VARCHAR2(10 BYTE)
);

INSERT INTO MEDIA VALUES ('10','TV');
INSERT INTO MEDIA VALUES ('20','PC');
INSERT INTO MEDIA VALUES ('30','MOBILE');